import { type NextPage } from "next";
import Head from "next/head";

const Explore: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <div className="flex flex-col items-center justify-center">
          <h1>Wanna create a room?</h1>
        </div>
      </main>
    </>
  );
};

export default Explore;