import { type NextPage } from "next";
import Head from "next/head";
import ConnectedMembers from "@/components/client/ConnectedMembers";

const Join: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Join a Room</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <h1 className="w-full py-6 px-10 md:px-20 border-b-2 border-stone-900 font-poppins text-4xl text-stone-300">Join a Room</h1>
        <section className="pt-10 px-10 md:px-20">
          <ConnectedMembers />
        </section>
      </main>
    </>
  );
};

export default Join;