import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import useRoomContext from "@/hooks/useRoomContext";
import MemberLink from "@/components/server/MemberLink";
import { UserData } from "@/context/SocketContext";
import { useEffect, Key } from "react";
import Question from "@/components/client/Question";

const Room: NextPage = () => {
  // redirect users without a session
  const router = useRouter();
  const { roomData } = useRoomContext();
  const { data: session, status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/");
    },
  });

  useEffect(() => {
    if (roomData?.roomID !== router.query.roomID)
      router.push("/rooms");
  }, [roomData?.roomID]);
  
  if ( status === "loading" ) {
    return <>Loading...</>; 
  }

  if ( roomData?.roomID !== router.query.roomID ) {
    return <>Not Authorized</>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page md:screen-h-wo-nav w-full md:grid grid-cols-12 grid-rows-3">
        <div className="row-span-2 col-start-0 col-span-3 p-4 bg-black md:border-r-2 border-stone-800">
          <h1 className="font-bold">Room {router.query.roomID}</h1>
          <p className="">Status: <span className="font-bold underline capitalize">{roomData?.status}</span></p>
          <ul className="mt-6 list-none">
            <p className="mb-4 border-b-2 border-stone-800 text-green-700 font-bold">Room Members</p>
            <div className="flex md:flex-col">
              { roomData?.members && roomData.members?.map((member: UserData, key: Key) => (
                  <li><MemberLink key={key} name={member.name} src={member.image} /></li>
              ))}
            </div>
          </ul>
        </div>

        <div className="col-start-4 col-span-9 row-span-2 p-10 py-20 md:py-10 h-auto centered">
          { roomData?.currentQuestion && <Question num={1} question={roomData?.currentQuestion}/> }
        </div>

        <div className="col-start-9 col-span-4 row-start-3 h-[15vh] md:h-full bg-black border-t-2 border-stone-800"></div>

        <div className="col-span-8 row-start-3 flex pb-10 h-[80vh] md:h-full bg-black border-t-2 md:border-r-2 border-stone-800">
          <form className="self-end flex-grow flex items-end px-10">
            <img className="w-10 h-10 rounded-full" src={session?.user?.image || "http://placeholder.co/500/500"} alt="user img" />
            <input className="mx-4 flex-grow p-2 h-12 outline-none border-b-2 border-stone-800 bg-transparent font-poppins text-stone-300 transition" type="text" placeholder="Send a message..." />
            <button className="h-10 p-3 centered rounded-lg font-bold text-stone-300 subpixel-antialiased bg-green-700 hover:bg-green-500 transition">Send</button>
          </form>
        </div>
        
      </main>
    </>
  );
};

export default Room;