import CreateRoom from "@/components/client/CreateRoom";
import JoinRoom from "@/components/server/JoinRoom";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import JoinableRooms from "@/components/client/JoinableRooms";

const Create: NextPage = () => {
  // redirect users without a session
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/");
    }
  });
  
  if ( status === "loading" ) {
    return <>Loading...</>; 
  }
  
  return (
    <>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page p-10">
        <JoinableRooms />
        <CreateRoom />
      </main>
    </>
  );
};

export default Create;