import CreateRoom from "@/components/client/CreateRoom";
import JoinRoom from "@/components/server/JoinRoom";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import JoinableRooms from "@/components/client/JoinableRooms";
import PoolMembers from "@/components/client/ConnectedMembers";
import RoomPanel from "@/components/server/RoomPanel";
import { useState } from "react";
import ToggleMatchMaking from "../../components/client/ToggleMatchMaking";

const Create: NextPage = () => {
  // redirect users without a session
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push("/");
    }
  });
  
  if ( status === "loading" ) {
    return <>Loading...</>; 
  }
  
  return (
    <>
      <Head>
        <title>Rooms</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page"> 

        <div className="h-fit md:h-[700px] p-4 md:grid grid-rows-5 grid-cols-3">
          <div className="row-span-3 col-span-2 centered p-4 "><RoomPanel /></div>
          <div className="md:row-span-5 col-start-3 p-4 centered w-full md:h-full"><PoolMembers /></div>
          <div className="row-span-2 col-span-2 w-full h-full p-4">
            <ToggleMatchMaking />
          </div>
        </div>

      </main>
    </>
  );
};

export default Create;